### ISSUE TITLE
Order-dependent circular import error

### ISSUE THREAD

**Issue by andrewtbiehl** [andrewtbiehl/gaslines#50]
Currently, attempting to import the `gaslines.solve` module without having previously imported the `gaslines.display` module results in an `ImportError`, illustrated below:
```python
>>> import gaslines.solve
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "./gaslines/gaslines/solve.py", line 7, in <module>
    import gaslines.display as display
  File "./gaslines/gaslines/display.py", line 9, in <module>
    from gaslines.solve import has_head
ImportError: cannot import name 'has_head' from partially initialized module 'gaslines.solve' (most likely due to a circular import) (./gaslines/gaslines/solve.py)
```

I agree with the diagnosis that this is "most likely due to a circular import", as a function from `solve` is indeed dependent on one from `display`, and vice versa.

In contrast, if the `display` module is instead imported _prior_ to importing `solve`, then this error is avoided:
```python
>>> import gaslines.display
>>> import gaslines.solve
```

In other words, whether such an error is encountered is dependent on the order in which modules are imported, which should not be the case.

In fact, even though it is true that all unit tests pass upon running a command like `invoke test`, this is most likely a consequence of the fortuitous order in which the modules of the `tests` package are loaded prior to running the tests. More specifically, it appears as though the error is avoided in this case simply because the modules are loaded in alphabetical order, and the `test_display` module, which imports the `display` module, alphabetically precedes the `test_solve` module, the sole test module dependent on the `solve` module. Indeed, renaming the `test_display` module (for example, to `test_zdisplay`) so that it alphabetically succeeds `test_solve` causes the error to manifest.

**Comment by andrewtbiehl** [comment]
This issue has been resolved via #51.
